# -*- coding: utf-8 -*-
"""Mundo 03 python curso em vídeo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vfZ1izEaYz6lW1lxyNBgmiGjgZNrdqoH
"""

#MUNDO 03 PYTHON

lanche = ('hambúrguer','pizza','pudim','suco','refri')

for c in range(0, len(lanche)):
  print(f'nós temos {lanche[c]}')

for c in lanche:
  print(f'nós temos {c}')

#desafio 72

contagem = ('Zero','Um','Dois','Três','Quatro','Cinco','Seis','Sete','Oito','Nove','Dez','Onze','Doze','Treze','Catorze','Quinze','Dezesseis','Dezessete','Dezoito','Dezenove','Vinte')

while True:
  num = int(input('Digite um número entre 0 e 20: '))
  if num >= 0 and num <= 20:
    print(f'''
Você digitou {num}, que se escreve {contagem[num]}''')
    a = input('''
Quer continuar? [s/n] ''').lower()
    if a == 's':
      print('Muito bem.')
    elif a == 'n':
      print('Ok.')
      break
    else:
      print('O meu senhor, tu é burro')
      break
  else:
    print('Preste atenção!')

#desafio 73

times = ('Palmeiras','Internacional','Flamengo','Fluminense','Corinthians','Athletico-PR','Atlético-MG','América-MG',
'Fortaleza','Botafogo','Santos','São Paulo','Bragantino','Goiás','Coritiba','Ceará SC','Cuiabá','Atlético-GO','Avaí','Juventude')

print(times)
print(f'''
{times[:5]} são os times que formam o G5.''')
print(f'''
{times[-4:]} são os times que serão rebaixados''')
print(f'''
Os times em ordem alfabética: {sorted(times)}''')

for cont in range(0, len(times)):
  if cont == 13:
    print(f'''
{times[cont]} está na 14ª posição.''')
    
#print(f'Goiás está na {times.index("Goiás")+1}ª posição.')

#desafio 74
from random import randint

lista = (randint(0,99),randint(0,99),randint(0,99),randint(0,99),randint(0,99))
#print(f'{lista} foram os número sorteados.')

for n in lista:
  
 print(f'{n} ', end='')

print(f'''
\nO maior Valor foi {max(lista)}''')
print(f'O Menor Valor foi {min(lista)}')

#desafio 75

cont = 0 #contagem de 9
par = 0 # numeros pares

a = int(input('Digite um valor: '))
if a == 9:
  cont += 1
elif a % 2 == 0:
  par += 1
b = int(input('Digite um valor: '))
if b == 9:
  cont += 1
elif b % 2 == 0:
  par += 1
c = int(input('Digite um valor: '))
if c == 9:
  cont += 1
elif c % 2 == 0:
  par += 1
d = int(input('Digite um valor: '))
if d == 9:
  cont += 1
elif d % 2 == 0:
  par += 1

lista = (a, b, c, d)

n3  = []
if a == 3:
  n3.append(1)
if b == 3:
  n3.append(2)
if c == 3:
  n3.append(3)
if d == 3:
  n3.append(4)


print(f'''

Os valores escolhidos foram: {lista}''')
print(f'''
O valor 9 apareceu {cont} vezes.''')
print(f'{par} número(s) par(es) foram digitados.')
print(f'O número 3 apareceu nas posições {n3}')

#Resolução Guanabara - desafio 75
num = ((int(input('Digite o número: ')), (int(input('Digite o número: '))), (int(input('Digite o número: '))), (int(input('Digite o número: ')))))

print(f'Você digitou os valores {num}')

print(f'O valor 9 apareceu {num.count(9)} vezes.')

if 3 in num:
  print(f'O valor 3 apareceu na {num.index(3)+1}ª posição.')
else:
  print('Não foi digitado o número 3.')
print(f'Os valores pares digitados foram ', end='')
for n in num:
  if n % 2 == 0:
    print(n, end=' ')

#desafio 76

from tabulate import tabulate

produtos = ( ['Caneta bic', 1.90], ['Apagador de quadro', 5.99], ['Caderno s/pauta', 13.99], ['Borracha', 1.35], ['Pillot', 4.50], ['Grafite 0.5', 3.99])

print(tabulate(produtos, headers = ['Produto', 'Preço R$']))

#Resolução Guanabara - desafio 76

produtos = ( 'Caneta bic', 1.90, 
            'Apagador de quadro', 5.99, 
            'Caderno s/pauta', 13.99, 
            'Borracha', 1.35, 
            'Pillot', 4.50, 
            'Grafite 0.5', 3.99)

print('-'*40)
print(f'{"PRODUTOS":^40}')
print('-'*40)

for c in range(0, len(produtos)):
  if c % 2 == 0:
    print(f'{produtos[c]:.<30}', end='')
  else:
    print(f'R${produtos[c]:>7.2f}')

#desafio 77

palavra = ('ameixa', 'vinho', 'azeite', 'ferro', 'abacate', 'miojo', 
           'pizza', 'beterraba', 'arroz', 'feijao', 'farofa', 
           'carne', 'leite', 'curso', 'papel')

for c in palavra:
  print(f'\nNa palavra {c.upper()} temos as vogais: ', end='')
  for letra in c:
    if letra.lower() in 'aeiou':
      print(letra, end =' ')

#INTRODUÇÃO A VARIÁVEIS COMPOSTAS (LISTAS PARTE 1)

'''lista = [1,2,3,4,5,6,7,8,9,0]
print(lista)

lista[0] = int(input('Novo valor: '))   # para substituir um valor específico da lista
print(lista)

lista.append(9999)    #para acrescentar um novo valor na lista pelo final
print(lista)

lista.insert(0,0)   #adicionando um novo valor na posição 0 reenumerando os outros valores
print(lista)

#formas de eliminar valores da lista

#del lista[3] #deleta o terceiro valor

#lista.pop() # deleta o um valor na posição indicada

#lista.remove(3) #remove o valor 3 da lista

#print(lista)'''

#para entender melhor
import time

faculdade = ['medicina', 'direito', 'engenharia', 'física', 'geografia', 'enfermagem', 'ciência de dados', 'educação física']
print('-'*40)
print(f'{"BEM-VINDO A NOSSA FACULDADE":^40}')
print('-'*40)
print('''
Catalogo de cursos: 
''')
for n in range(0, len(faculdade)):
  print(f'{faculdade[n]}')

novo = str(input('Ficou faltando algum curso? [s/n] ')).lower()

while True:
  if novo == 's':
    faculdade.append(str(input('Qual curso gostaria de incluir? ')))
  elif novo == 'n':
    print('''
Fim''')
    break
  else:
    print('''
Error''')
    break
  print('''
Aguarde enquanto incluimos o novo curso''')

  time.sleep(4)

  print('''

Lista de cursos atualizada!!!
  ''')
  time.sleep(2)

  print('''
Catalogo de cursos: 
  ''')
  for n in range(0, len(faculdade)):
    print(f'{faculdade[n]}')
  break

#desafio 78
lista = list()

for c in range(0,5):
  num = lista.append(int(input(f'{c+1}º valor da lista: ')))


print(f'*'*30)
print(f'O maior valor digitado foi: {max(lista)} e está nas posições: ', end='')
for i, v in enumerate(lista):
  if v == max(lista):
    print(f'{i+1} ', end='')

print(f'''
O menor valor digitado foi: {min(lista)} e está nas posições: ''',end='')
for i, v in enumerate(lista):
  if v == min(lista):
    print(f'{i+1} ', end='')
print()
print('*'*30)

#desagio 79
import time
lista = list()

while True:
  num = int(input('Digite um número: '))
  if num not in lista:
    lista.append(num)
    time.sleep(0.5)
    print('Valor adicionado com sucesso!')
  else:
    time.sleep(0.5)
    print('Valor duplicado! Não foi adicionado novamente.')
  cont = input('Gostari de continuar? [s/n] ').lower()
  if cont == 'n':
    break
  elif cont != 's' and cont != 'n':
    print('error')
    break

print(f'Você adicionou os valores {sorted(lista)}')

#desafio 80 - lista organizada sem o sort

#Resolução Guanabara
lista = []
for c in range(0,5):
  n = int(input('Digite um valor: '))
  if c == 0 or n > lista[-1]:
    lista.append(n)
  else:
    pos = 0
    while pos < len(lista):
      if n <= lista[pos]:
        lista.insert(pos, n)
        print(f'Adicinado na posição {pos}')
        break
      pos += 1

print('-='*30)
print(f'Os valores digitados em ordem foram: {lista}')

#desafio 81

lista = []
g = False


while True:
  num = int(input('Digite um número: '))
  if num == 5:
    g = True
  lista.append(num)
  cont = input('Deseja continuar? [s/n] ').lower()
  if cont == 'n':
    break
  if cont != 's' and cont != 'n':
    print('ERROR')
    break

print(f'''
Os valores digitados foram {lista}''')
print(f'''
Foram digitados: {len(lista)} valores''')

lista.sort(reverse = True)
print(f'''
Os valores em ordem decrescente: {lista}''')

if g == True:
  print('''
O número 5 está na lista.''')
else:
  print('''
O número 5 não está na lista.''')

valores = ['8','2','5','4','9','3','0']
valores.sort(reverse = True)
print(valores)

#desafio 82

lista = list()
par = list()
impar = list()

while True:
  num = int(input('Digite um valor: '))
  lista.append(num)
  if num % 2 == 0:
    par.append(num)
  else: 
    impar.append(num)
  cont = input('Deseja continuar? [s/n] ').lower()
  if cont == 'n':
    break
  elif cont != 'n' and cont != 's':
    print('error')
    break

print(f'''A lista digitada foi: {sorted(lista)}
Valores pares: {sorted(par):}
Valores impares: {sorted(impar):}''')

#desafio 83 -  verificação de parenteses na frase

exp = str(input('Digite a sua expressão: '))
lista = list()

for simb in exp:
  if simb == '(':
    lista.append('(')
  elif simb == ')':
    if len(lista) > 0:
      lista.pop()
    else:
      lista.append(')')
      break
if len(lista) == 0:
  print('Sua expressão está correta.')
else:
  print('Sua expressão está errada.')

#time 3x3 LoL
import random
nomes = ['Fã do Billy Joel', 'xcopox', 'Mytologicbn', 'Guziin', 'Rmlx926', 'Titanio22']
random.shuffle(nomes)

A = list()
B = list()

player = 0

for cont in nomes:
  player += 1
  if player <= 3:
    A.append(cont)
  else:
    B.append(cont)

print(f'''Time Azul: {A}

Time Vermelho: {B}''')

a = [5,10,15,1,13,8]
b = ['janeiro','fevereiro','março','abril','maio','junho']
import matplotlib.pyplot as plt

plt.scatter(b,a)

plt.xlabel('mês')
plt.ylabel('Dias de chuva')
plt.title('Dias com chuva em 2022')

plt.show()

#aula 18

teste = list()
teste.append('Gustavo')
teste.append(40)
galera = list()
galera.append(teste)
print(galera)

#desafio 84 - cadastro
pessoas = list()
dados = list()
maiorpeso = list()
menorpeso = list()

num = 0

while True:
  n = input('Nome: ')
  i = int(input('Peso (kg): '))
  num += 1
  dados.append(n)
  dados.append(i)
  pessoas.append(dados[:])
  dados.clear()
  cont = input('Deseja continuar? [s/n]').lower()
  if cont != 's':
    break

for pessoa in pessoas:
  if pessoa[1] >=80:
    maiorpeso.append(pessoa[0])
  else:
    menorpeso.append(pessoa[0])

print(f'Foram cadastradas {num} pessoas.')
print(f'As pessoas de peso maior que 80kg são: {maiorpeso}')
print(f'As pessoas de peso menor que 80kg são: {menorpeso}')

#resolução guanabara desafio 84
temp = []
princ = []
mai = men = 0

while True:
  temp.append(str(input('Nome: ')))
  temp.append(float(input('Peso: ')))
  if len(princ) == 0:
    mai = men = temp[1]
  else:
    if temp [1] > mai:
      mai = temp[1]
    if temp[1] < men:
      men = temp[1]
    princ.append(temp[:])
    temp.clear()
    resp = str(input('Quer continuar? [s/n]'))
    if resp in 'Nn':
      break

print('-='*30)
print(f'Ao todo, você cadastrou {len(princ)} pessoas.')
print(f'O maior peso foi de {mai}kg. Peso de ', end='')
for p in princ:
  if p[1] == mai:
    print(f'[{p[0]}]', end='')
print()
print(f'O menor peso foi de {men}kg. Peso de ',end='')
for p in princ:
  if p[1] == men:
    print(f'[{p[0]}]', end='')
print()

#desafio 85 - soma de impar e par
total = list()
par = list()
impar = list()


for c in range(0,7):
  total.append(int(input('Digite um número: ')))
  total.sort()

for n in range(0,7):
  if total[n] % 2 == 0:
    par.append(total[n])
  else:
    impar.append(total[n])

print(f'Os número pares digitados foram: {par}')
print(f'Os números impares digitados foram: {impar}')

#DESAFIO 85 - soma de impar e par
total = [[],[]]
for c in range(0,7):
  num = int(input('digite o número: '))
  if num % 2 == 0:
    total[0].append(num)
  else:
    total[1].append(num)
  
total[0].sort()
total[1].sort()
print(f'Os número pares digitados foram: {total[0]}')
print(f'Os números impares digitados foram: {total[1]}')

#DESAFIO 86 - matriz

matriz = [[0,0,0], [0,0,0], [0,0,0]]
for l in range(0, 3):
  for c in range(0, 3):
    matriz[l][c] = int(input(f'Digite um valor para [{l}, {c}]: '))

print('-='*30)
for l in range(0,3):
  for c in range(0, 3):
    print(f'[{matriz[l][c]:^5}]', end='')
  print()

#DESAFIO 87 - matriz

matriz = [[0,0,0], [0,0,0], [0,0,0]]
spar = mai = scol = 0
#codigo para formar a matriz
for l in range(0, 3):
  for c in range(0, 3):
    matriz[l][c] = int(input(f'Digite um valor para [{l}, {c}]: '))
#codigo para formatar a matriz na tela
print('-='*30)
for l in range(0,3):
  for c in range(0, 3):
    print(f'[{matriz[l][c]:^5}]', end='')
    if matriz[l][c] % 2 == 0:
      spar += matriz[l][c]
  print()
print('-='*30)
print(f'a soma dos valores pares é: {spar}')
for l in range(0, 3):
  scol += matriz[l][2]
print(f'a soma da terceira coluna é: {scol}')
for c in range(0 ,3):
  if c == 0:
    mai = matriz[1][c]
  elif matriz[1][c] > mai:
    mai =matriz[1][c]
print(f'O maior valor da segunda linha é: {mai}')

#DESAFIO 88 - jogos da mega-sena
import random
from time import sleep
mega = list()
jogos = list()
print('-'*30)
print('     JOGO DA MEGA SENA     ')
print('-'*30)
quantidade = int(input('Quantos jogos você quer? '))
total = 1
while total <= quantidade:
  c = 0
  while True:
    num = random.randint(1, 60)
    if num not in mega:
      mega.append(num)
      c += 1
    if c >= 6:
      break
  mega.sort()
  jogos.append(mega[:])
  mega.clear()
  total += 1
print()
print('-='*4, 'JOGOS GERADOS', '-='*4)
for i, l in enumerate(jogos):
  print(f'Jogo {i+1}: {l}')
  sleep(1)
print('-='*5, 'BOA SORTE!', '-='*5)

#jogo do bicho
import random
from time import sleep
mega = list()
jogos = list()
print('-'*30)
print('     JOGO DO BICHO     ')
print('-'*30)
quantidade = int(input('Quantos jogos você quer? '))
total = 1
while total <= quantidade:
  c = 0
  while True:
    num = random.randint(1, 99)
    if num not in mega:
      mega.append(num)
      c += 1
    if c >= 3:
      break
  mega.sort()
  jogos.append(mega[:])
  mega.clear()
  total += 1
print()
print('-='*4, 'JOGOS GERADOS', '-='*4)
for i, l in enumerate(jogos):
  print(f'Jogo {i+1}: {l}')
  sleep(1)
print('-='*5, 'BOA SORTE!', '-='*5)

#desafio 89
notas = list()

while True:
  aluno = str(input('Aluno: '))
  n1 = float(input('Nota 1: '))
  n2 = float(input('Nota 2: '))
  media = (n1 + n2)/2
  notas.append([aluno, [n1, n2], media])
  cont = str(input('Deseja continuar? [s/n] '))
  if cont in 'Nn':
    break

print('-='*30)
print(f'{"No.":<4}{"NOME":<10}{"MÉDIA":>8}')
print('-'*26)

for i, a in enumerate(notas):
  print(f'{i:<4}{a[0]:<10}{a[2]:>8.1f}')
while True:
  print('-'*35)
  opc  = int(input('Mostrar notas de qual aluno? (999 interrompe): '))
  if opc == 999:
    break
  if opc <= len(notas) - 1:
    print(f'Notas de {notas[opc][0]} são {notas[opc][1]}: ')
print('FINALIZADO')

#aula 19
dados = dict()
dados = {'nome':'Pedro', 'idade':'25'}
dados['sexo']='M'
del dados['idade']

print(dados)


valorant = {'Duelista':'Reyna', 'Controlador':'Cypher','Sentinela':'Viper', 'Iniciador':'Fade'}
print(valorant.keys())
print(valorant.values())
print(valorant.items())

for p,d in valorant.items():
  print(f'A personagem {d} é {p}')

brasil = list()
Estado1 = {'Estado':'Rio de Janeiro', 'Capital':'Rio de Janeiro', 'Região':'Sudeste'}
Estado2 = {'Estado':'São Paulo', 'Capital':'São Paulo', 'Região':'Sudeste'}
Estado3 = {'Estado':'Bahia','Capital':'Salvador','Região':'Nordeste'}
Estado4 = {'Estado':'Amazonas','Capital':'Manaus','Região':'Norte'}
brasil.append(Estado1)
brasil.append(Estado2)
brasil.append(Estado3)
brasil.append(Estado4)
print(brasil)

players = dict()
lista = list()

for c in range (0, 3):
  players['nickname'] = str(input('Nickname: '))
  players['elo'] = str(input('Rank: '))
  lista.append(players.copy())

for c in lista:
  for k, v in c.items():
    print(f'{k}: {v}  ', end=' ')
  print()

#desafio 90

aluno = dict()

aluno['Nome'] = str(input('Nome do Aluno: '))
aluno['Media'] = float(input(f'Média do aluno {aluno["Nome"]}: '))
if aluno['Media'] >= 7.0:
  aluno['Resultado'] = 'Aprovado'
elif 4.0 <= aluno['Media'] < 7.0:
  aluno['Resultado'] = 'Prova final'
else:
  aluno['Resultado'] = 'Reprovado'

print('-'*30)
print(f'Aluno: {aluno["Nome"]}')
print(f'Média: {aluno["Media"]}'),
print(f'Situação: {aluno["Resultado"]}')

#desafio 91
from random import randint
from time import sleep
from operator import itemgetter

jogo  = {'Jogador 1': randint(1,6),
         'Jogador 2': randint(1,6),
         'Jogador 3': randint(1,6),
         'Jogador 4': randint(1,6),}
ranking = list()
        
print('Valores Sorteados: ')
print()
for k, v in jogo.items():
  print(f'O {k} tirou {v} no dado')
  sleep(1)
print()
print('-='*20)
print(' == RANKING DOS JOGADORES ==')
print()
ranking = sorted(jogo.items(), key=itemgetter(1), reverse=True)
for i, v in enumerate(ranking):
  print(f'{i+1}º Lugar: {v[0]} com {v[1]}')
  sleep(1)

#desafio 92

cadastro = dict()

cadastro['Nome'] = str(input('Nome: '))
cadastro['Ano'] = int(input('Ano de Nascimento: '))
cadastro['CTPS'] = int(input('CTPS (0 caso não tenha): '))
if cadastro['CTPS'] != 0:
  cadastro['Contratacao'] = int(input('Ano de contratação: '))
  cadastro['Salario'] = float(input('Salário: R$'))
  cadastro['Aposentadoria'] = int(cadastro['Contratacao'] - cadastro['Ano'] + 35)

print('-='*30)
for k, v in cadastro.items():
  print(f'{k} tem o valor de {v}')

#desafio 93

jogador = dict()
partidas = list()

jogador['nome'] = str(input('Nome do Jogador: '))
tot = int(input(f'Quantas partidas {jogador["nome"]} jogou? '))
for c in range(0, tot):
  partidas.append(int(input(f'Quantos gols na partida {c+1}: ')))
jogador['gols'] = partidas[:]
jogador['total'] = sum(partidas)

for k,v in jogador.items():
  print(f'O campo {k} em o valor {v}')

print(jogador)

print('-='*30)
print(f'O jogador {jogador["nome"]} jogou {tot} partidas.')
for i,a in enumerate(jogador['gols']):
  print(f' --- na partida {i+1}, fez {a} gols.')
print(f'No total ele marcou {jogador["total"]} gols.')

#desafio 94

pessoa = dict()
lista = list()
media = list()
mulheres = list()
aaaa = list()
num = 1

while True:
  pessoa['nome'] = str(input('Nome: '))
  while True:
    pessoa['sexo'] = str(input('Sexo: [m/f] '))
    if pessoa['sexo'] not in 'MmFf':
      print('ERROR, porfavor digite apenas m ou f')
    if pessoa['sexo'] == 'f':
      mulheres.append(pessoa['nome'])
    if pessoa['sexo'] in 'MmFf':
      break
  pessoa['idade'] = int(input('Idade: '))
  media.append(pessoa['idade'])
  lista.append(pessoa.copy())
  cont = str(input('Deseja continuar? [s/n] '))
  if cont in 'Ss':
    num += 1
  elif cont in 'Nn':
    break
  else: 
    print('ERROR')
    break
print(f'{num} pessoas se cadastraram.')
meedia = (float(sum(media)/num))
print(f'A média das idades cadastradas é: {meedia}')
print(f'Mulheres cadastradas: {mulheres}')

#resolução guanabara desafio 94

galera = list()
pessoa = dict()
soma = média = 0
while True:
  pessoa.clear()
  pessoa['nome'] = str(input('Nome: '))
  while True:
    pessoa['sexo'] = str(input('Sexo: ')).upper() [0]
    if pessoa['sexo'] in 'MF':
      break
    print('ERROR! Digite somente M ou F.')
  pessoa['idade'] = int(input('Idade: '))
  soma += pessoa['idade']
  galera.append(pessoa.copy())
  while True:
    resp = str(input('Deseja continuar? [s/n] ')).upper() [0]
    if resp in 'SN':
      break
    print('ERROR! Digite apenas S ou N.')
  if resp == 'N':
    break
print('-='*30)
print(f'A) Ao todo {len(galera)} pessoas cadastradas.')
média = soma / len(galera)
print(f'B) A média de idade é de {média:5.2f} anos')
print(f'C) As mulheres cadastradas foram ', end='')
for p in galera:
  if p['sexo'] in 'Ff':
    print(f'{p["nome"]}', end=' ')
print()
print('D) Lista das pessoas que estão acima de média: ')
for p in galera:
  if p['idade'] >= média:
    print('   ')
    for k,v in p.items():
      print(f'{k} = {v}', end=' ')
    print()
print('<< ENCERRADO >>')

#desafio 95

time = list()
jogador = dict()
partidas = list()

while True:
  jogador.clear()
  jogador['nome'] = str(input('Nome do Jogador: '))
  tot = int(input(f'Quantas partidas {jogador["nome"]} jogou? '))
  partidas.clear()
  for c in range(0, tot):
    partidas.append(int(input(f'      Quantos gols na partida {c}? ')))
  jogador['gols'] = partidas[:]
  jogador['total'] = sum(partidas)
  time.append(jogador.copy())
  while True:
    resp = str(input('Deseja continuar [s/n]? ')).upper() [0]
    if resp in 'SN':
      break
    print('ERRO! Responda apenas S ou N.')
  if resp == 'N':
    break
print('-='*30)
print('cod ', end='')
for i in jogador.keys():
  print(f'{i:<15}', end='')
print()
print('-'*40)
for k, v in enumerate(time):
  print(f'{k:>3} ', end='')
  for d in v.values():
    print(f'{str(d):<15}', end='')
  print()
print('-'*40)
while True:
  busca = int(input('Mostrar dados de qual jogador? '))
  if busca == 999:
    break
  if busca >= len(time):
    print(f'Error! não existe jogador com o código {busca}')
  else:
    print(f'-- LEVANTAMENTO DOS DADOS DO JOGADOR {time[busca]["nome"]}:')
    for i, g in enumerate(time[busca]['gols']):
      print(f'    No jogo {i+1} fez {g} gols.')
print('-'*40)
print('VOLTE SEMPRE!')